// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportik_API.Dal;

#nullable disable

namespace Sportik_API.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sportik_API.Dal.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgSrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "OPTIMUM NUTRITION 100% WHEY GOLD STANDARD",
                            Price = 450m,
                            Title = "OPTIMUM NUTRITION",
                            TypeOfProduct = "protein",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/optimum.jpg?updatedAt=1686178714662"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "SCITEC NUTRITION 100% WHEY PROTEIN PROFESSIONAL",
                            Price = 530m,
                            Title = "SCITEC NUTRITION",
                            TypeOfProduct = "protein",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/scitec.jpg?updatedAt=1686178715027"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "AMIX ISOPRIME CFM",
                            Price = 770m,
                            Title = "AMIX ISOPRIME",
                            TypeOfProduct = "protein",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/optimum.jpg?updatedAt=1686178714662"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "AMIX ISOPRIMESCITEC NUTRITION 100% WHEY ISOLATE",
                            Price = 1030m,
                            Title = "SCITEC NUTRITION",
                            TypeOfProduct = "protein",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/scitecN.jpg?updatedAt=1686178714431"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "IRONMAXX 100% WHEY PROTEIN",
                            Price = 960m,
                            Title = "IRONMAXX",
                            TypeOfProduct = "protein",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/ironmax.jpg?updatedAt=1686178718701"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "SPORTER CREATINE MONOHYDRATE",
                            Price = 830m,
                            Title = "SPORTER CREATINE",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/monohydrate.jpg?updatedAt=1686178714523"
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "SPORTER CREATINE HCL 1400",
                            Price = 750m,
                            Title = "SPORTER CREATINE HCL",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/hcl.jpg?updatedAt=1686178718775"
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "AMIX AMIXPRО CREATINE HCL",
                            Price = 630m,
                            Title = "AMIXPRО CREATINE",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/amixpro.jpg?updatedAt=1686178718387"
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "TREC NUTRITION CM3 HMB - 200 КАПС",
                            Price = 590m,
                            Title = "TREC NUTRITION",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/trecN.png?updatedAt=1686178714986"
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "TREC NUTRITION CM3 POWDER",
                            Price = 730m,
                            Title = "TREC NUTRITION CM3",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/trecN2.png?updatedAt=1686178714889"
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "TREC NUTRITION CM3 PRO+ - 200 КАПС",
                            Price = 450m,
                            Title = "TREC NUTRITION CM3",
                            TypeOfProduct = "creatine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/trecN3.png?updatedAt=1686178714929"
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "AMIX XFAT 2IN1 SHOT",
                            Price = 780m,
                            Title = "AMIX XFAT 2IN1",
                            TypeOfProduct = "l-carnitine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/XFat.jpg?updatedAt=1686178714900"
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "HAYA LABS ACETYL L-CARNITINE",
                            Price = 450m,
                            Title = "HAYA LABS",
                            TypeOfProduct = "l-carnitine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/acetyl.jpg?updatedAt=1686178718108"
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "HAYA LABS ADVANCED LIQUID",
                            Price = 305m,
                            Title = "HAYA LABS ADVANCED",
                            TypeOfProduct = "l-carnitine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/liquid.jpg?updatedAt=1686178718796"
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "TREC NUTRITION L-CARNITINE 3000",
                            Price = 450m,
                            Title = "TREC NUTRITION",
                            TypeOfProduct = "l-carnitine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/trec.png?updatedAt=1686178714843"
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "SPORTER L- CARNITINE 60000 - 0,5Л",
                            Price = 380m,
                            Title = "SPORTER L- CARNITINE",
                            TypeOfProduct = "l-carnitine",
                            imgSrc = "https://ik.imagekit.io/w5l3jpc0n/sporter.png?updatedAt=1686178714667"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
